
!! @author Paul Baumeister
!! @version 3.0
!!
!! interface towards the plotting tool xmGRACE 5.0
module Grace
implicit none
  private ! default for this module namespace
  character(len=*), parameter, private :: sym = 'xmG' !! module symbol

  public :: grace_plot
  public :: test

  interface grace_plot
    module procedure plot
  endinterface

  integer, parameter :: o=0 ! 6: stdout, 0: no output

  integer, parameter :: GRACE_VERSIONNUMBER = 50120

  integer, private                        :: page_size(1:2) = (/792, 612/)

  character(len=*), parameter   :: default_description = &
    'Grace project auto-generated by the grace module by Paul Baumeister.'

  integer, parameter :: default_font = 0 ! Helvetica
  real, parameter    :: default_font_size = 1.5
  real, parameter    :: default_line_width = 3.0
  real, parameter    :: default_symbol_size = 0.333
  integer, parameter :: default_symbol_type = 0 ! none
  integer, parameter :: default_tick_number = 6

  integer, save      :: font        = default_font
  real, save         :: font_size   = default_font_size
  real, save         :: line_width  = default_line_width
  real, save         :: symbol_size = default_symbol_size
  integer, save      :: symbol_type = default_symbol_type
  integer, save      :: tick_number = default_tick_number

  character(len=*), parameter :: FONTNAME = "Helvetica"
!   character(len=*), parameter :: FONTNAMEs(0:26) = &
!    (/ &
! !      "Times-Roman                  ", &
!       "Helvetica                    ", &
!       "Times-Italic                 ", &
!       "Times-Bold                   ", &
!       "Times-BoldItalic             ", &
! !       "Helvetica                    ", &
!       "Times-Roman                  ", &
!       "Helvetica-Oblique            ", &
!       "Helvetica-Bold               ", &
!       "Helvetica-BoldOblique        ", &
!       "Courier                      ", &
!       "Courier-Oblique              ", &
!       "Courier-Bold                 ", &
!       "Courier-BoldOblique          ", &
!       "Symbol                       ", &
!       "ZapfDingbats                 ", &
!       "Helvetica-Narrow             ", &
!       "Helvetica-Narrow-Bold        ", &
!       "Helvetica-Narrow-BoldOblique ", &
!       "Helvetica-Narrow-Oblique     ", &
!       "NewCenturySchlbk-Bold        ", &
!       "NewCenturySchlbk-BoldItalic  ", &
!       "NewCenturySchlbk-Italic      ", &
!       "NewCenturySchlbk-Roman       ", &
!       "Palatino-Bold                ", &
!       "Palatino-BoldItalic          ", &
!       "Palatino-Italic              ", &
!       "Palatino-Roman               ", &
!       "ZapfChancery-MediumItalic    " /)
! 
!   integer, parameter, private             :: FONTNUMBERs(0:26) = &
!     (/ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,15,16, &
!       17,18,20,21,22,23,24,25,26,27,33 /) 

  integer, parameter, private             :: COLOR_RGBs(3,0:15) = &
    reshape( (/ &
        255, 255, 255, &
          0,   0,   0, &
        255,   0,   0, &
          0, 255,   0, &
          0,   0, 255, &
        255, 255,   0, &
        188, 143, 143, &
        220, 220, 220, &
        148,   0, 211, &
          0, 255, 255, &
        255,   0, 255, &
        255, 165,   0, &
        114,  33, 188, &
        103,   7,  72, &
         64, 224, 208, &
          0, 139,   0    /) , (/3,16/) )


  character(len=*), parameter, private    :: COLORNAMEs(0:15) = &
   (/ &
      "white    ", & ! 0
      "black    ", & ! 1
      "red      ", & ! 2
      "green    ", & ! 3
      "blue     ", & ! 4
      "yellow   ", & ! 5
      "brown    ", & ! 6
      "grey     ", & ! 7
      "violet   ", & ! 8
      "cyan     ", & ! 9
      "magenta  ", & ! 10
      "orange   ", & ! 11
      "indigo   ", & ! 12
      "maroon   ", & ! 13
      "turquoise", & ! 14
      "green4   " /) ! 15

  integer, parameter, private :: myColorOrder(1:10) = (/ 1, 2, 15, 4, 8, 10, 11, 12, 14, 3 /)
  integer, parameter, private :: myLineTypeOrder(1:2) = (/ 1, 2 /)
  character(len=*), parameter, private :: axis(1:2) = (/ '@    xaxis  ', '@    yaxis  ' /)

  contains

  integer function plot( file, ydata, & ! required args
                   xdata, labels, title, subtitle, legends, scheme ) result( ios )! optional args
    character(len=*), intent(in)                :: file
    real, intent(in)                            :: ydata(1:,1:)
    real, intent(in), optional                  :: xdata(1:)
    character(len=*), intent(in), optional      :: labels(2)
    character(len=*), intent(in), optional      :: title
    character(len=*), intent(in), optional      :: subtitle
    character(len=*), intent(in), optional      :: legends(:)
    character(len=*), intent(in), optional      :: scheme

    character(len=*), parameter                 :: fun = ' plot: '
    character(len=*), parameter                 :: HLINE = '\hline'
    character(len=*), parameter                 :: LINEBREAK = ' \\'
    integer, parameter                          :: LINETYPE_SCHEME_NOLINE         = 0
    integer, parameter                          :: LINETYPE_SCHEME_LINE           = 1
    integer, parameter                          :: LINETYPE_SCHEME_BANDSTRUCTURE  = 2
    integer, parameter                          :: COLOR_SCHEME_BLACK_AND_WHITE = 0
    integer, parameter                          :: COLOR_SCHEME_DARKCOLORS      = 1
    integer, parameter                          :: COLOR_SCHEME_DARKCOLORS2ND   = 4
    integer, parameter                          :: COLOR_SCHEME_BANDSTRUCTURE   = 2
    integer, parameter                          :: LINESTYLE_SCHEME_ALLSOLID      = 0
    integer, parameter                          :: LINESTYLE_SCHEME_DASH2ND       = 1
    integer, parameter                          :: LINESTYLE_SCHEME_BANDSTRUCTURE = 2
    integer, parameter                          :: LINESTYLE_SCHEME_VARIOUS       = 3
    integer :: u ! usually iounit_t :: u
    integer                                     :: ns, is, np, ip, icolor, ir, ia
    character(len=3)                            :: legend_on_off = 'on '
    real                                        :: minmax(1:2,1:2), view(1:2,1:2), mmdiff(1:2), &
                                                   tick_major(1:2), view_enlargement(1:2) = 0.05
    integer, allocatable                        :: line_type(:), line_color(:), line_style(:), symbol_type(:)
    integer                                     :: color_scheme, linestyle_scheme, linetype_scheme
!     integer                                     :: ifont, time(8)
!     character(len=24)                           :: timestamp

    if(o>0) write(o,'(9A)') sym, fun, 'write file "', file, '".'

    np = size( ydata, 1 )
    ns = size( ydata, 2 )

    ! for the y-axis
    minmax(1,2) = minval( ydata )
    minmax(2,2) = maxval( ydata )
    ! for the x-axis
    if( present( xdata ) ) then
      minmax(1,1) = minval( xdata )
      minmax(2,1) = maxval( xdata )
    else  ! present( xdata )
      minmax(1,1) = real(  0 )
      minmax(2,1) = real( np )
    endif ! present( xdata )

    ! for x and y axis:
    mmdiff(:) = minmax(2,:) - minmax(1,:)
    view(1,:) = minmax(1,:) - view_enlargement(:) * mmdiff(:) 
    view(2,:) = minmax(2,:) + view_enlargement(:) * mmdiff(:)

    if( minmax(1,1) == 0. ) view(1,1) = 0.
    if( abs(minmax(1,2)) < 1.E-12 ) view(1,2) = 0.
    if(o>0) write(o,'(3A,4ES10.2,9A)') sym, fun, 'minmax =[', minmax, ' ]'
    if(o>0) write(o,'(3A,4ES10.2,9A)') sym, fun, '  view =[', view  , ' ]'

    tick_number = default_tick_number

    do ia = 1, 2
      tick_major(ia) = tick_with_affinity( (minmax(2,ia)-minmax(1,ia)), tick_number )
    enddo ! ia


    font_size = default_font_size
    font      = default_font
    symbol_type = 0 ! none
    ! color_scheme = COLOR_SCHEME_BLACK_AND_WHITE ! black and white
    color_scheme = COLOR_SCHEME_DARKCOLORS


    ! set as default
    linetype_scheme = LINETYPE_SCHEME_LINE
    linestyle_scheme = LINESTYLE_SCHEME_ALLSOLID

    if( present( scheme ) ) then

      selectcase( scheme )
      case( 'b&w' )
        color_scheme     = COLOR_SCHEME_BLACK_AND_WHITE ! black and white
        linestyle_scheme = LINESTYLE_SCHEME_VARIOUS
      case( 'bandstructure' )
        linetype_scheme  = LINETYPE_SCHEME_BANDSTRUCTURE
        color_scheme     = COLOR_SCHEME_BANDSTRUCTURE
        linestyle_scheme = LINESTYLE_SCHEME_BANDSTRUCTURE
        symbol_size      = 0.1
      case( 'dash2nd' )
        color_scheme     = COLOR_SCHEME_DARKCOLORS2ND
        linestyle_scheme = LINESTYLE_SCHEME_DASH2ND
      case( 'dots' )
        linetype_scheme  = LINETYPE_SCHEME_NOLINE
        color_scheme     = COLOR_SCHEME_DARKCOLORS
      case( '1line&dots' )
        linetype_scheme  = LINETYPE_SCHEME_BANDSTRUCTURE
        color_scheme     = COLOR_SCHEME_DARKCOLORS
        linestyle_scheme = LINESTYLE_SCHEME_BANDSTRUCTURE
        symbol_size      = 0.5
      case default
        color_scheme     = COLOR_SCHEME_DARKCOLORS
        linestyle_scheme = LINESTYLE_SCHEME_DASH2ND
      endselect ! scheme

    endif ! present( scheme )

    allocate( line_type(ns), line_color(ns), line_style(ns), symbol_type(ns), stat=is )
    if( is /= 0 ) stop 'xmG: failed to allocate! (line 261)'

    ! defaults
    line_type   = 1 ! 1: straight line  0: no line
    symbol_type = 0 ! no symbol

    selectcase( linetype_scheme )
    case( LINETYPE_SCHEME_NOLINE )
      line_type       = 0 ! 1: straight line  0: no line
      symbol_type     = 1 ! 1: straight line  0: no line
    case( LINETYPE_SCHEME_BANDSTRUCTURE )
      line_type(2:)   = 0 ! 1: straight line  0: no line
      symbol_type(2:) = 1 ! 1: straight line  0: no line
    endselect ! linetype_scheme


    selectcase( color_scheme )
    case( COLOR_SCHEME_BLACK_AND_WHITE )
      line_color = 1
    case( COLOR_SCHEME_DARKCOLORS )
      do is = 1, ns
        line_color(is) = myColor( is )
      enddo ! is
    case( COLOR_SCHEME_DARKCOLORS2ND )
      do is = 1, ns, 2
        line_color(is) = myColor( (is+1)/2 )
      enddo ! is
      do is = 2, ns, 2
        line_color(is) = myColor( is/2 )
      enddo ! is
    case( COLOR_SCHEME_BANDSTRUCTURE )
      line_color( 1) = 2 ! red
      line_color(2:) = 1 ! black
    case default
      line_color = 1 ! all black
    endselect ! color_scheme


    selectcase( linestyle_scheme )
    case( LINESTYLE_SCHEME_DASH2ND )
      do is = 1, ns, 2
        line_style(is)  = 1 ! solid
      enddo ! is
      do is = 2, ns, 2
        line_style(is)  = 3 ! dashed  ! 2 ! dotted
      enddo ! is
    case( LINESTYLE_SCHEME_VARIOUS )
      do is = 1, ns
        line_style(is) = is
      enddo ! is
    case( LINESTYLE_SCHEME_BANDSTRUCTURE )
      line_style( 1) = 3 ! dashed
      line_style(2:) = 1 ! solid
    case default
      line_style  = 1 ! all solid
    endselect ! linestyle_scheme




    u = 12 ! unit for writing the file
    open(unit=u,file=file,status='unknown',iostat=ios)
    if( ios /= 0 ) stop 'xmG: plot: error in opening the file.'

!---------------------------------------------------------------------
write(u,'(A)')      '# Grace project file'
write(u,'(A)')      '#'
write(u,'(A,I0)')   '@version ', GRACE_VERSIONNUMBER
write(u,'(2(A,I0))')'@page size ', page_size(1), ', ', page_size(2)
write(u,'(3A)')     '@description "', default_description, '"'
write(u,'(A)')      '@page scroll 5%'
write(u,'(A)')      '@page inout 5%'
write(u,'(A)')      '@link page off'
! do ifont = 0, 26
!   write(u,'(A,I0,9A)') &
!     '@map font ', &
!     FONTNUMBERs(IFONT),' to "', &
!     trim(FONTNAMEs(ifont)),'", "', trim(FONTNAMEs(ifont)), '"'
! enddo ! ifont

!   write(u,'(A,I0,9A)') '@map font ', 0,' to "', &
!     trim(FONTNAMEs(default_font)),'", "', trim(FONTNAMEs(default_font)), '"'

  ! only default font (map 0)
  font = 0
  write(u,'(A,I0,9A)') '@map font ', font,' to "', trim(FONTNAME),'", "', trim(FONTNAME), '"'

do icolor = 0, 15
  write(u,'(A,I0,A,3(I0,A),9A)') &
    '@map color ', icolor,' to (', &
    COLOR_RGBs(1,icolor), ',', &
    COLOR_RGBs(2,icolor), ',', &
    COLOR_RGBs(3,icolor), '), "', &
    trim(COLORNAMEs(icolor)), '"'
enddo ! icolor
write(u,'(A)')      '@reference date 0'
write(u,'(A)')      '@date wrap off'
write(u,'(A)')      '@date wrap year 1950'
write(u,'(A,F4.1)') '@default linewidth', default_line_width
write(u,'(A)')      '@default linestyle 1' ! solid
write(u,'(A)')      '@default color 1' ! black
write(u,'(A)')      '@default pattern 1'
write(u,'(A,I0)')      '@default font ', default_font
write(u,'(A)')      '@default char size 1.000000'
write(u,'(A)')      '@default symbol size 1.000000'
write(u,'(A)')      '@default sformat "%.8g"'
write(u,'(A)')      '@background color 0' ! white
write(u,'(A)')      '@page background fill on'
write(u,'(A)')      '@timestamp off'
! write(u,'(A)')      '@timestamp 0.03, 0.03'
! write(u,'(A)')      '@timestamp color 1'
! write(u,'(A)')      '@timestamp rot 0'
! write(u,'(A,I0)')      '@timestamp font ', default_font
! write(u,'(A)')      '@timestamp char size 1.000000'

! ! reproduce the timestamp from the date of creation
! call date_and_time( values=time )
! write(unit=timestamp,fmt='(I4,I3,I3,I3,A1,I2,A1,I2)') &
!   time(1:3), time(5), ':', time(6), ':', time(7)
! !write(u,'(A)')      '@timestamp def "Sun Aug 10 16:29:44 2008"'
! write(u,'(9A)')     '@timestamp def "', trim(timestamp), '"'

do ir = 0, 4
write(u,'(A,I0,A)') '@r', ir, ' off'
write(u,'(A,I0,A)') '@link r', ir, ' to g0'
write(u,'(A,I0,A)') '@r', ir, ' type above'
write(u,'(A,I0,A)') '@r', ir, ' linestyle 1'
write(u,'(A,I0,A,F4.1)') '@r', ir, ' linewidth', default_line_width
write(u,'(A,I0,A)') '@r', ir, ' color 1'
write(u,'(A,I0,A)') '@r', ir, ' line 0, 0, 0, 0'
enddo ! ir

write(u,'(A)')      '@g0 on'
write(u,'(A)')      '@g0 hidden false'
write(u,'(A)')      '@g0 type XY'
write(u,'(A)')      '@g0 stacked false'
write(u,'(A)')      '@g0 bar hgap 0.000000'
write(u,'(A)')      '@g0 fixedpoint off'
write(u,'(A)')      '@g0 fixedpoint type 0'
write(u,'(A)')      '@g0 fixedpoint xy 0.000000, 0.000000'
write(u,'(A)')      '@g0 fixedpoint format general general'
write(u,'(A)')      '@g0 fixedpoint prec 6, 6'
write(u,'(A)')      '@with g0'

write(u,'(4(A,ES12.4))')  '@    world ', view(1,1), ',', view(1,2), ',', view(2,1), ',', view(2,2)
write(u,'(9A)')     '@    stack world 0, 0, 0, 0'
write(u,'(9A)')     '@    znorm 1'
write(u,'(9A)')     '@    view 0.15, 0.10, 1.25, 0.85'
if( present( title ) ) then
write(u,'(9A)')     '@    title "', trim(title), '"'
write(u,'(A,I0)')     '@    title font ', default_font
write(u,'(A,F5.2)') '@    title size ', font_size
write(u,'(9A)')     '@    title color 1'
endif ! present( title )
if( present( subtitle ) ) then
write(u,'(9A)')     '@    subtitle "', trim(subtitle), '"'
write(u,'(A,I0)')     '@    subtitle font ', default_font
write(u,'(A,F5.2)') '@    subtitle size ', font_size
write(u,'(9A)')     '@    subtitle color 1'
endif ! present( subtitle )
write(u,'(9A)')     '@    xaxes scale Normal'
write(u,'(9A)')     '@    yaxes scale Normal'
write(u,'(9A)')     '@    xaxes invert off'
write(u,'(9A)')     '@    yaxes invert off'

do ia = 1, 2
write(u,'(9A)')     axis(ia), 'on'
write(u,'(9A)')     axis(ia), 'type zero false'
write(u,'(9A)')     axis(ia), 'offset 0.000000 , 0.000000'
write(u,'(9A)')     axis(ia), 'bar off'
write(u,'(9A)')     axis(ia), 'bar color 1'
write(u,'(9A)')     axis(ia), 'bar linestyle 1'
write(u,'(2A,F4.1)')axis(ia), 'bar linewidth', default_line_width
if( present( labels ) ) then
  write(u,'(9A)')     axis(ia), 'label "', trim(labels(ia)), '"'
else  ! present( labels )
  write(u,'(9A)')     axis(ia), 'label ""'
endif ! present( labels )

write(u,'(9A)')     axis(ia), 'label layout para'
write(u,'(9A)')     axis(ia), 'label place auto'
write(u,'(2A,F5.2)')     axis(ia), 'label char size ', default_font_size
write(u,'(2A,I3)')  axis(ia), 'label font ', default_font
write(u,'(9A)')     axis(ia), 'label color 1'
write(u,'(9A)')     axis(ia), 'label place normal'
write(u,'(9A)')     axis(ia), 'tick on'
write(u,'(2A,ES10.2)')axis(ia), 'tick major ', tick_major(ia)
write(u,'(9A)')     axis(ia), 'tick minor ticks 0'
write(u,'(9A)')     axis(ia), 'tick default 6'
write(u,'(9A)')     axis(ia), 'tick place rounded true'
write(u,'(9A)')     axis(ia), 'tick in' ! or 'out'
write(u,'(9A)')     axis(ia), 'tick major size 1.000000'
write(u,'(9A)')     axis(ia), 'tick major color 1'
write(u,'(2A,F4.1)')axis(ia), 'tick major linewidth', line_width
write(u,'(9A)')     axis(ia), 'tick major linestyle 1'
write(u,'(9A)')     axis(ia), 'tick major grid off'
write(u,'(9A)')     axis(ia), 'tick minor color 1'
write(u,'(2A,F4.1)')axis(ia), 'tick minor linewidth', line_width
write(u,'(9A)')     axis(ia), 'tick minor linestyle 1'
write(u,'(9A)')     axis(ia), 'tick minor grid off'
write(u,'(9A)')     axis(ia), 'tick minor size 0.500000'
write(u,'(9A)')     axis(ia), 'ticklabel on'
write(u,'(9A)')     axis(ia), 'ticklabel format general'
write(u,'(9A)')     axis(ia), 'ticklabel prec 5'
write(u,'(9A)')     axis(ia), 'ticklabel formula ""'
write(u,'(9A)')     axis(ia), 'ticklabel append ""'
write(u,'(9A)')     axis(ia), 'ticklabel prepend ""'
write(u,'(9A)')     axis(ia), 'ticklabel angle 0'
write(u,'(9A)')     axis(ia), 'ticklabel skip 0'
write(u,'(9A)')     axis(ia), 'ticklabel stagger 0'
write(u,'(9A)')     axis(ia), 'ticklabel place normal'
write(u,'(9A)')     axis(ia), 'ticklabel offset auto'
write(u,'(9A)')     axis(ia), 'ticklabel offset 0.000000 , 0.010000'
write(u,'(9A)')     axis(ia), 'ticklabel start type auto'
write(u,'(9A)')     axis(ia), 'ticklabel start 0.000000'
write(u,'(9A)')     axis(ia), 'ticklabel stop type auto'
write(u,'(9A)')     axis(ia), 'ticklabel stop 0.000000'
write(u,'(2A,F5.2)')     axis(ia), 'ticklabel char size ', default_font_size
write(u,'(2A,I0)')  axis(ia), 'ticklabel font ', default_font
write(u,'(9A)')     axis(ia), 'ticklabel color 1'
write(u,'(9A)')     axis(ia), 'tick place both' ! both sides
write(u,'(9A)')     axis(ia), 'tick spec type none'
enddo ! ia

write(u,'(9A)')     '@    legend ', legend_on_off
write(u,'(9A)')     '@    legend loctype view'
write(u,'(9A)')     '@    legend 0.80, 0.4'
write(u,'(9A)')     '@    legend box color 1'
write(u,'(9A)')     '@    legend box pattern 1'
write(u,'(A,F4.1)') '@    legend box linewidth', line_width
write(u,'(9A)')     '@    legend box linestyle 1'
write(u,'(9A)')     '@    legend box fill color 0'
write(u,'(9A)')     '@    legend box fill pattern 1'
write(u,'(A,I0)')  '@    legend font ', default_font
write(u,'(A,F5.2)')     '@    legend char size ', default_font_size
write(u,'(9A)')     '@    legend color 1'
write(u,'(9A)')     '@    legend length 4'
write(u,'(9A)')     '@    legend vgap 1'
write(u,'(9A)')     '@    legend hgap 1'
write(u,'(9A)')     '@    legend invert false'

write(u,'(9A)')     '@    frame ', 'type 0'
write(u,'(9A)')     '@    frame ', 'linestyle 1'
write(u,'(2A,F4.1)')'@    frame ', 'linewidth', line_width
write(u,'(9A)')     '@    frame ', 'color 1'
write(u,'(9A)')     '@    frame ', 'pattern 1'
write(u,'(9A)')     '@    frame ', 'background color 0'
write(u,'(9A)')     '@    frame ', 'background pattern 0'

do is = 1, ns

  write(u,'(9A)')   '@    s', i2l(is-1), ' hidden false'
  write(u,'(9A)')   '@    s', i2l(is-1), ' type xy'
  write(u,'(3A,I0)')     '@    s', i2l(is-1), ' symbol ', symbol_type(is)
  write(u,'(3A,F6.3)')   '@    s', i2l(is-1), ' symbol size ', symbol_size
  write(u,'(3A,I0)') '@    s', i2l(is-1), ' symbol color ', line_color(is)
  write(u,'(9A)')   '@    s', i2l(is-1), ' symbol pattern 1'
  write(u,'(3A,I0)') '@    s', i2l(is-1), ' symbol fill color ',line_color(is)
  write(u,'(9A)')   '@    s', i2l(is-1), ' symbol fill pattern 0'
  write(u,'(3A,F4.1)')   '@    s', i2l(is-1), ' symbol linewidth', line_width
  write(u,'(9A)')   '@    s', i2l(is-1), ' symbol linestyle 1'
  write(u,'(9A)')   '@    s', i2l(is-1), ' symbol char 65'
  write(u,'(3A,I0)')   '@    s', i2l(is-1), ' symbol char font ', default_font
  write(u,'(9A)')   '@    s', i2l(is-1), ' symbol skip 0'
  write(u,'(3A,I0)')     '@    s', i2l(is-1), ' line type ', line_type(is)
  write(u,'(3A,I0)')   '@    s', i2l(is-1), ' line linestyle ', line_style(is)
  write(u,'(3A,F4.1)')   '@    s', i2l(is-1), ' line linewidth', line_width
  write(u,'(3A,I0)')     '@    s', i2l(is-1), ' line color ', line_color(is)
  write(u,'(9A)')   '@    s', i2l(is-1), ' line pattern 1'
  write(u,'(9A)')   '@    s', i2l(is-1), ' baseline type 0'
  write(u,'(9A)')   '@    s', i2l(is-1), ' baseline off'
  write(u,'(9A)')   '@    s', i2l(is-1), ' dropline off'
  write(u,'(9A)')   '@    s', i2l(is-1), ' fill type 0'
  write(u,'(9A)')   '@    s', i2l(is-1), ' fill rule 0'
  write(u,'(9A)')   '@    s', i2l(is-1), ' fill color 1'
  write(u,'(9A)')   '@    s', i2l(is-1), ' fill pattern 1'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue off'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue type 2'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue char size 1.000000'
  write(u,'(3A,I0)')    '@    s', i2l(is-1), ' avalue font ', default_font
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue color 1'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue rot 0'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue format general'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue prec 3'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue prepend ""'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue append ""'
  write(u,'(9A)')   '@    s', i2l(is-1), ' avalue offset 0.000000 , 0.000000'
  write(u,'(9A)')   '@    s', i2l(is-1), ' errorbar off'
! @    s0 errorbar place both
! @    s0 errorbar color 1
! @    s0 errorbar pattern 1
! @    s0 errorbar size 1.000000
! @    s0 errorbar linewidth 2.0
! @    s0 errorbar linestyle 1
! @    s0 errorbar riser linewidth 1.0
! @    s0 errorbar riser linestyle 1
! @    s0 errorbar riser clip off
! @    s0 errorbar riser clip length 0.100000
if( present( legends ) ) then
  write(u,'(9A)')   '@    s', i2l(is-1), ' comment "', trim(legends(is)), '"'
  write(u,'(9A)')   '@    s', i2l(is-1), ' legend  "', trim(legends(is)), '"'
else  ! present( legends )
  write(u,'(9A)')   '@    s', i2l(is-1), ' comment "', '"'
  write(u,'(9A)')   '@    s', i2l(is-1), ' legend  "', '"'
endif ! present( legends )

enddo ! is (data sets)


if( present( xdata ) ) then
  do is = 1, ns
    write(u,'(2A)')    '@target G0.S', i2l(is-1)
    write(u,'(A)')      '@type xy'
    do ip = 1, np
      write(u,'(2ES16.6E2)') xdata(ip), ydata(ip,is)
    enddo ! ip
  enddo ! is
else ! present( xdata )
  do is = 1, ns
    write(u,'(2A)')    '@target G0.S', i2l(is-1)
    write(u,'(A)')      '@type xy'
    do ip = 1, np
      write(u,'(I8,ES16.6E2)') ip, ydata(ip,is)
    enddo ! ip
  enddo ! is
endif ! present( xdata )

write(u,'(A)')      '&', ' '
!-----------------------------------------------------------------------
    close(unit=u,iostat=ios)
  endfunction ! plot

  integer function myColor( i )
    integer, parameter        :: n = size(myColorOrder,1)
    integer, intent(in)       :: i
    integer                   :: j
    j = max( 1, i )
    do while( j > n )
      j = j - n
    enddo ! while j > n
    myColor = myColorOrder( j )
  endfunction ! myColor



  character(len=2) function i2l( i )
    integer, intent(in)       :: i
    write(unit=i2l, fmt='(I2)' ) i
    i2l = adjustl(i2l)
  endfunction ! i2l


  real function tick_with_affinity( length, nticks, allowedfractions ) result( t )
    real, intent(in)                      :: length
    integer, intent(in)                   :: nticks
    integer, intent(in), optional         :: allowedfractions(:)

    character(len=*), parameter           :: fun = ' tick_with_affinity: '
    integer, parameter                    :: NA = 6
    real, parameter                       :: allowed(NA) = (/.5,1.,2.,5.,10.,20./)
    integer                               :: nt, ilogt, ia
    real                                  :: logt, dec, lngth
    real                                  :: a(NA)

    if( length <= 0. ) then
      write(o,'(3A,ES10.2)') sym, fun, 'negative axis length impossible, received length =', length
    endif ! length <= 0
    lngth = abs(length)

    nt = max( 2, nticks )
    t = lngth/real(nt)
    logt = log10(t)

    ! write(6,'(3A,F10.6)') sym, fun, 'log(tick) =', logt
    ilogt = int( logt )

    dec = logt - real(ilogt)

    do ia = 1, NA
      a(ia) = log10( allowed(ia) )
    enddo ! ia

    ia = 1
    do while( abs( dec - a(ia) ) > abs( dec - a(ia+1) ) )
      ia = ia + 1
    enddo ! ia
    dec = a(ia)

    logt = real(ilogt) + dec

    t = 10.0**logt

    ! write(6,'(3A,F10.6)') sym, fun, 'dec       =', dec
    ! write(6,'(3A,ES10.2)') sym, fun, 't         =', t
    ! write(6,'(3A,  I10)') sym, fun, 'nticks    =', nint(length/t)

  endfunction ! tick_with_affinity


  integer function test( ) result( ist )
    integer, parameter :: N = 100
    integer :: i, j
    real    :: r, rdata(N,5)

    do i = 1, N
      r = real(5*(i-1))/real(N)
      do j = 1, 5
        rdata(i,j) = r**j * exp(-j*r)
      enddo ! 12
    enddo ! i

    ist = plot( file='r2expmr.agr', ydata=rdata )
    ! ist =  plot( file, ydata, xdata, labels, title, subtitle, legends )
    write(*,*)'xmgrace r2expmr.agr'
  endfunction ! test

endmodule ! grace
